spring:
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.entity
  mapper-locations: classpath:mapper/*.xml

---
#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver